# Generated by Django 5.1.1 on 2024-10-19 03:42

import shortuuid.main
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_game', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameroom',
            name='game_name',
            field=models.CharField(default=shortuuid.main.ShortUUID.uuid, max_length=50, unique=True),
        ),
    ]
