# Generated by Django 5.1.1 on 2024-10-19 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_game', '0002_alter_gameroom_game_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameroom',
            name='game_name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
