# Generated by Django 5.1.1 on 2024-10-20 01:24

import shortuuid.main
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_game', '0004_gamemodel_alter_goal_game_delete_game'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamemodel',
            name='game_end',
        ),
        migrations.RemoveField(
            model_name='gamemodel',
            name='game_start',
        ),
        migrations.RemoveField(
            model_name='gamemodel',
            name='is_finished',
        ),
        migrations.RemoveField(
            model_name='gamemodel',
            name='players',
        ),
        migrations.RemoveField(
            model_name='gamemodel',
            name='score_player_1',
        ),
        migrations.RemoveField(
            model_name='gamemodel',
            name='score_player_2',
        ),
        migrations.RemoveField(
            model_name='gamemodel',
            name='winner',
        ),
        migrations.AlterField(
            model_name='gamemodel',
            name='room_name',
            field=models.CharField(default=shortuuid.main.ShortUUID.uuid, max_length=80, unique=True),
        ),
    ]
