# Generated by Django 5.1.1 on 2024-10-20 02:12

import shortuuid.main
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_game', '0010_remove_goal_game_remove_goal_player_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamemodel',
            name='room_name',
            field=models.CharField(default=shortuuid.main.ShortUUID.uuid, max_length=80, unique=True),
        ),
    ]
