# Generated by Django 5.1.1 on 2024-10-20 02:45

import shortuuid.main
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_game', '0011_alter_gamemodel_room_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='gamemodel',
            name='players',
            field=models.ManyToManyField(blank=True, related_name='room_player', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='gamemodel',
            name='room_name',
            field=models.CharField(blank=True, default=shortuuid.main.ShortUUID.uuid, max_length=80, unique=True),
        ),
    ]
