# Generated by Django 5.1.1 on 2024-10-20 02:57

import shortuuid.main
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_game', '0015_alter_gamemodel_room_name_alter_gamemodel_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamemodel',
            name='room_name',
            field=models.CharField(blank=True, default=shortuuid.main.ShortUUID.uuid, max_length=80, unique=True),
        ),
        migrations.AlterModelTable(
            name='gamemodel',
            table='game_rooms',
        ),
    ]
