# Generated by Django 5.1.1 on 2024-10-20 03:17

import shortuuid.main
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_game', '0017_alter_gamemodel_options_alter_gamemodel_room_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gamemodel',
            options={},
        ),
        migrations.AlterField(
            model_name='gamemodel',
            name='room_name',
            field=models.CharField(blank=True, default=shortuuid.main.ShortUUID.uuid, max_length=80, unique=True),
        ),
    ]
