# Generated by Django 5.1.1 on 2024-10-21 04:27

import shortuuid.main
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_game', '0022_alter_gamemodel_room_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamemodel',
            name='gameroom_name',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='gamemodel',
            name='room_name',
            field=models.CharField(blank=True, default=shortuuid.main.ShortUUID.uuid, max_length=80, unique=True),
        ),
    ]
